spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: test-user
    password: test-password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
